# Generated by Django 2.1 on 2018-08-25 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='logosConcursos')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_terminacion', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=500)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video_participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_participante', models.CharField(max_length=200)),
                ('apellidos_participante', models.CharField(max_length=200)),
                ('correo_participante', models.CharField(max_length=200)),
                ('video_original', models.FileField(upload_to='videosOriginales')),
                ('video_porcesado', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=500)),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'En proceso'), (2, 'Convertido')])),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcm.Concurso')),
            ],
        ),
    ]
